# Site settings
title: Data Science Workshop
subtitle: Programming for Data Science
description: |
    Data science has evolved significantly in the past decade, with the convergence of computer science and statistics.
    As statisticians, we are trained to understand data using statistical and mathematical models.
    However, data scientists can spend up to 80% of their time pulling, organizing, and cleaning data, 
    which requires a basic understanding of databases. Furthermore, machine learning positions are 
    increasingly focused on software engineering rather than math and theory. Many data science interviews 
    include questions about algorithms, data structures, and databases, which are not typically covered in a statistics curriculum. </br>
    
    This course will cover how data science has evolved in the past decade, how working in the industry differs from academia, 
    and the data science interview process. Additionally, the course will cover engineering aspects and teach 
    the programming fundamentals necessary for a career in data science, which are often tested in data science 
    and machine learning interviews. The course will use SQL and Python.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "jsm2023.scientistcafe.com" # the base hostname & protocol for your site
syllabus: "https://jsm2023.scientistcafe.com/course-syllabus/"
githubdir: "happyrabbit/JSM2023"


# Author/user information
email: longqiman@gmail.com
github_username:  happyrabbit
authorurl: "https://scientistcafe.com/"
# address: |
#    San Francisco, California


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
